title: Kanthaus
metadata:
    description: 'prevent waste - promote sharing'

summary:
    enabled: true
    size: 100

author:
    name: Kanthaus
    email: hello@kanthaus.online

taxonomies: [tag,author]
