image: monachus/hugo

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
# Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$DEPLOY_SSH_KEY")
  - hugo
  - rsync --delete -e "ssh -o StrictHostKeyChecking=no" -a --chmod=g+w public/ $DEPLOY_URL
  artifacts:
    paths:
    - public
  only:
  - master
